let adminWeekId=null;
function adminMsg(msg,ok=false){const el=document.getElementById('adminMessage');if(!el)return;el.textContent=msg;el.classList.toggle('ok',ok)}
function adminSide(m,side){const name=side==='a'?m.manager_a:m.manager_b;const p1=side==='a'?m.player_a:m.player_b;const p2=side==='a'?m.player_a_two:m.player_b_two;const type=side==='a'?m.card_type_a:m.card_type_b;const score=side==='a'?m.score_a:m.score_b;if(!p1)return `<div class="admin-side pending"><strong>${esc(name)}</strong><span>⏳ Captain not submitted</span></div>`;if(type==='autograph_defense')return `<div class="admin-side defense"><strong>${esc(name)}</strong><span>🛡️ ${esc(p1)} · DEFENSE</span><small>Pure protection · no ticket movement</small></div>`;const players=[p1,p2].filter(Boolean);return `<div class="admin-side"><strong>${esc(name)}</strong>${players.map((p,i)=>`<label>${esc(p)} PPR<input class="admin-score" type="number" step="0.1" inputmode="decimal" data-player="${esc(p)}" placeholder="PPR score" /></label>`).join('')}<small>${type==='dual_power'?'⚡ Dual Power · combined automatically':'🏈 Player Card'}${score!==null&&score!==undefined?` · Current ${fmtScore(score)}`:''}</small></div>`}
function renderAdmin(){const root=document.getElementById('adminMatchups');if(!root||!profile?.is_commissioner)return;document.getElementById('adminWeek').textContent=state.week||'—';root.innerHTML=(state.matchups||[]).map((m,i)=>{const submitted=!!m.player_a&&!!m.player_b;const final=String(m.matchup_status||'').toLowerCase()==='final';return `<article class="panel admin-matchup"><div class="matchup-top"><span>MATCHUP ${i+1}</span><span>${final?'FINAL':submitted?'READY':'WAITING'}</span></div><h3>${esc(m.manager_a)} <em>vs</em> ${esc(m.manager_b)}</h3>${adminSide(m,'a')}${adminSide(m,'b')}<div class="admin-actions"><button class="btn blue save-scores" data-matchup="${esc(m.matchup_id)}" ${!submitted||final?'disabled':''}>Save Scores</button><button class="btn yellow finalize-matchup" data-matchup="${esc(m.matchup_id)}" ${!submitted||final?'disabled':''}>Finalize Matchup</button></div></article>`}).join('')||'<div class="panel">No matchups found.</div>'}
async function loadAdmin(){if(!profile?.is_commissioner)return;renderAdmin();const {data,error}=await client.from('weeks').select('id,week_number').eq('season_id',state.season_id||'c748c464-49ee-45ea-8511-a28acb95229a').eq('week_number',state.week||1).single();if(error){console.error(error);adminMsg('Could not load the current week.');return}adminWeekId=data.id}
async function saveScores(card){if(!adminWeekId)return adminMsg('Week is still loading. Try again.');const inputs=[...card.querySelectorAll('.admin-score')];if(!inputs.length)return adminMsg('This matchup has no manual player scores to enter.');const filled=inputs.filter(x=>x.value!=='');if(!filled.length)return adminMsg('Enter at least one PPR score first.');adminMsg('Saving scores…');try{for(const input of filled){const {error}=await client.rpc('set_weekly_player_score',{p_week_id:adminWeekId,p_player_name:input.dataset.player,p_ppr_score:Number(input.value),p_source:'manual'});if(error)throw error}await loadLiveState();renderAdmin();adminMsg('✓ Scores saved. Review the matchup, then finalize when ready.',true)}catch(err){console.error(err);adminMsg(err.message||'Could not save scores.') }}
async function finalizeMatchup(id){if(!confirm('Finalize this matchup? This can move 1 ticket and marks both Captain cards played.'))return;adminMsg('Finalizing matchup…');const {data,error}=await client.rpc('finalize_card_captain_matchup',{p_matchup_id:id});if(error){console.error(error);adminMsg(error.message||'Could not finalize matchup.');return}await loadLiveState();renderAdmin();adminMsg(`✓ ${data?.result||'Matchup finalized.'}`,true)}
document.addEventListener('click',e=>{const save=e.target.closest('.save-scores');if(save)saveScores(save.closest('.admin-matchup'));const fin=e.target.closest('.finalize-matchup');if(fin)finalizeMatchup(fin.dataset.matchup)});
const oldGo=go;go=function(id){oldGo(id);if(id==='admin'&&profile?.is_commissioner)loadAdmin()};
const oldRenderState=renderState;renderState=function(){oldRenderState();if(document.querySelector('[data-screen="admin"]')?.classList.contains('active'))loadAdmin()};