const SUPABASE_URL='https://prupedxpebntoqhilrzi.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_TZahmAv5GD3bv4LaHfma_w_i0daueMI';
const AUTH_FUNCTION=`${SUPABASE_URL}/functions/v1/card-captain-auth`;
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);

const managers=[
  ['Karen Marek (Mom)','karen-marek'],['Nick Larscheid','nick-larscheid'],['Thomas Larscheid','thomas-larscheid'],['Brian Larscheid','brian-larscheid'],['Joseph Larscheid','joseph-larscheid'],['Adam Ibrahim','adam-ibrahim'],['Tyler Lant','tyler-lant'],['Zach Lant','zach-lant'],['Kenn Linehan','kenn-linehan'],['Ryan Dietz','ryan-dietz']
];
const baseTabs=[['home','🏠','Home'],['play','⚡','Play'],['cards','🃏','Cards'],['history','📚','History'],['tickets','🎟️','Tickets'],['rules','📜','Rules']];
const adminTab=['admin','🛠️','Admin'];
const privateScreens=new Set(['play','cards','history','admin']);
let state={week:1,demo_mode:true,matchups:[],tickets:[]};
let session=null;
let profile=null;
let authMode='signin';
let previewUrl=null;

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtScore(v){const n=Number(v);return Number.isFinite(n)?n.toFixed(1):'—'}
function captainLabel(player1,player2,type){if(type==='dual_power'&&player2)return `${player1} + ${player2}`;return player1||'Captain pending'}
function matchupCard(m,i){const a=Number(m.score_a),b=Number(m.score_b),aHas=Number.isFinite(a),bHas=Number.isFinite(b);const aWin=aHas&&bHas&&a>b,bWin=aHas&&bHas&&b>a;return `<article class="panel matchup-card"><div class="matchup-top"><span>MATCHUP ${i+1}</span><span>${state.demo_mode?'DEMO LIVE':esc(m.matchup_status||'LIVE').toUpperCase()}</span></div><div class="team-row ${aWin?'winner':''}"><div><div class="manager-name">${esc(m.manager_a)}</div><div class="captain-name">${esc(captainLabel(m.player_a,m.player_a_two,m.card_type_a))}</div></div><div class="score">${fmtScore(m.score_a)}</div></div><div class="team-row ${bWin?'winner':''}"><div><div class="manager-name">${esc(m.manager_b)}</div><div class="captain-name">${esc(captainLabel(m.player_b,m.player_b_two,m.card_type_b))}</div></div><div class="score">${fmtScore(m.score_b)}</div></div></article>`}
function ticketCards(){return (state.tickets||[]).map((t,i)=>`<article class="panel ticket-card"><span>${i+1}. ${esc(t.name)}</span><span class="mini-ticket">🎟️ ${Number(t.tickets)||0}</span></article>`).join('')}
function myTickets(){if(!profile)return null;const row=(state.tickets||[]).find(t=>t.name===profile.display_name);return row?Number(row.tickets)||0:null}
function myCurrentMatchup(){if(!profile)return null;return (state.matchups||[]).find(m=>m.manager_a===profile.display_name||m.manager_b===profile.display_name)||null}
function renderPlayContext(){const el=document.getElementById('playContext');if(!el)return;if(!profile){el.innerHTML='<strong>Sign in to see your matchup.</strong>';return}const m=myCurrentMatchup();if(!m){el.innerHTML=`<strong>Week ${state.week||1}</strong><span>No matchup found for ${esc(profile.display_name)}.</span>`;return}const opponent=m.manager_a===profile.display_name?m.manager_b:m.manager_a;el.innerHTML=`<div><span class="play-kicker">WEEK ${state.week||1} MATCHUP</span><strong>${esc(profile.display_name)} <em>vs</em> ${esc(opponent)}</strong><small>Your Captain will be attached to this fantasy matchup automatically.</small></div>`}
function renderState(){document.getElementById('matchups').innerHTML=(state.matchups||[]).map(matchupCard).join('')||'<div class="panel">No matchups yet.</div>';document.getElementById('ticketsHome').innerHTML=ticketCards();document.getElementById('ticketsFull').innerHTML=ticketCards();const banner=document.querySelector('.preview-banner');if(banner)banner.textContent=`LIVE SUPABASE DATA · Week ${state.week||1} · ${state.demo_mode?'Demo scoring':'League scoring'} · Unused cards remain private`;const eyebrow=document.querySelector('.hero .eyebrow');if(eyebrow)eyebrow.textContent=`WEEK ${state.week||1} · ${state.demo_mode?'DEMO MODE':String(state.week_status||'OPEN').toUpperCase()}`;renderIdentity();renderPlayContext()}
async function loadLiveState(){try{const res=await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_public_card_captain_state`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'Content-Type':'application/json'},body:'{}'});if(!res.ok)throw new Error(`Supabase ${res.status}`);const data=await res.json();if(data&&typeof data==='object'){state=data;renderState()}}catch(err){console.error('Live state load failed',err);const banner=document.querySelector('.preview-banner');if(banner)banner.textContent='LIVE DATA TEMPORARILY UNAVAILABLE · Showing app shell'}}
function currentTabs(){return profile?.is_commissioner?[...baseTabs,adminTab]:baseTabs}
function renderNav(){const tabs=currentTabs();document.getElementById('bottomNav').style.gridTemplateColumns=`repeat(${tabs.length},1fr)`;document.getElementById('bottomNav').innerHTML=tabs.map(t=>`<button class="nav-btn ${t[0]==='home'?'active':''}" data-nav="${t[0]}"><span class="ico">${t[1]}</span>${t[2]}</button>`).join('')}
function go(id){if(privateScreens.has(id)&&!session){openAuth('signin');return}if(id==='admin'&&!profile?.is_commissioner){id='home'}document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));history.replaceState(null,'',id==='home'?location.pathname:`#${id}`);window.scrollTo({top:0,behavior:'smooth'});if(id==='play')renderPlayContext()}
function renderIdentity(){const btn=document.getElementById('authButton');const chip=document.getElementById('myTicketChip');if(profile){btn.innerHTML=`${esc(profile.display_name)} <span>• ${profile.is_commissioner?'Commissioner':'Manager'}</span>`;btn.title='Tap to sign out';const t=myTickets();chip.innerHTML=`🎟️ <strong>${t===null?'—':t}</strong>`}else{btn.textContent='Sign in / Claim account';btn.title='';chip.innerHTML='🎟️ <strong>—</strong>'}}
function setAuthMode(mode){authMode=mode;document.querySelectorAll('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));document.getElementById('claimFields').hidden=mode!=='claim';document.getElementById('confirmPinLabel').hidden=mode!=='claim';document.getElementById('authSubmit').textContent=mode==='claim'?'Claim Account':'Sign In';setAuthMessage('')}
function openAuth(mode='signin'){setAuthMode(mode);document.getElementById('authModal').hidden=false;document.body.classList.add('modal-open');setTimeout(()=>document.getElementById(mode==='claim'?'inviteCode':'pinInput').focus(),50)}
function closeAuth(){document.getElementById('authModal').hidden=true;document.body.classList.remove('modal-open');setAuthMessage('')}
function setAuthMessage(msg,ok=false){const el=document.getElementById('authMessage');el.textContent=msg;el.classList.toggle('ok',ok)}
function setCaptainMessage(msg,ok=false){const el=document.getElementById('captainMessage');if(!el)return;el.textContent=msg;el.classList.toggle('ok',ok)}
function selectedManager(){const slug=document.getElementById('managerSelect').value;return managers.find(m=>m[1]===slug)}
function loginEmail(slug){return `${slug}@cardcaptain.app`}
async function signIn(slug,pin){const {data,error}=await client.auth.signInWithPassword({email:loginEmail(slug),password:pin});if(error)throw new Error(error.message==='Invalid login credentials'?'Name or PIN is incorrect.':error.message);return data.session}
async function claimAccount(slug,inviteCode,pin){const res=await fetch(AUTH_FUNCTION,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({action:'claim',login_slug:slug,invite_code:inviteCode,pin})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error([data.error,data.detail].filter(Boolean).join(' — ')||'Could not claim account.');return data}
async function submitAuth(){const manager=selectedManager();const pin=document.getElementById('pinInput').value.trim();if(!manager)return setAuthMessage('Choose your name.');if(!/^\d{6}$/.test(pin))return setAuthMessage('PIN must be exactly 6 digits.');const button=document.getElementById('authSubmit');button.disabled=true;button.textContent='Working…';setAuthMessage('');try{if(authMode==='claim'){const invite=document.getElementById('inviteCode').value.trim();const confirm=document.getElementById('confirmPinInput').value.trim();if(pin!==confirm)throw new Error('PINs do not match.');await claimAccount(manager[1],invite,pin);await signIn(manager[1],pin);setAuthMessage('Account claimed. You are signed in.',true)}else await signIn(manager[1],pin);setTimeout(closeAuth,450)}catch(err){setAuthMessage(err.message||'Could not sign in.')}finally{button.disabled=false;button.textContent=authMode==='claim'?'Claim Account':'Sign In'}}
async function loadProfile(){if(!session?.user){profile=null;renderIdentity();renderNav();renderPlayContext();return}const {data,error}=await client.from('manager_profiles').select('id,display_name,is_commissioner,login_slug,account_status').eq('auth_user_id',session.user.id).single();if(error){console.error('Profile load failed',error);profile=null}else profile=data;renderIdentity();renderNav();renderPlayContext()}
async function handleSession(newSession){session=newSession;await loadProfile();const hash=location.hash.slice(1);if(hash==='admin'&&!profile?.is_commissioner)go('home')}
function resetCaptainForm(){document.getElementById('captainForm')?.reset();document.getElementById('playerTwoLabel').hidden=true;document.getElementById('photoName').textContent='Required for Year 1 card verification.';document.getElementById('photoPrompt').textContent='Take or upload a photo of your physical card';const preview=document.getElementById('photoPreview');if(preview){preview.hidden=true;preview.removeAttribute('src')}if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}}
function safeExtension(file){const fromName=(file.name||'').split('.').pop().toLowerCase();if(/^[a-z0-9]{2,5}$/.test(fromName))return fromName;const map={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/heic':'heic','image/heif':'heif'};return map[file.type]||'jpg'}
async function submitCaptain(event){event.preventDefault();if(!session?.user||!profile){openAuth('signin');return}const photo=document.getElementById('cardPhoto').files[0];const cardType=document.getElementById('cardType').value;const playerOne=document.getElementById('playerOne').value.trim();const playerTwo=document.getElementById('playerTwo').value.trim();if(!photo)return setCaptainMessage('Take or upload a card photo first.');if(!playerOne)return setCaptainMessage('Enter Player 1.');if(cardType==='dual_power'&&!playerTwo)return setCaptainMessage('Dual Power cards need Player 2.');const button=document.getElementById('captainSubmit');button.disabled=true;button.textContent='Uploading card…';setCaptainMessage('');let photoPath=null;try{const ext=safeExtension(photo);photoPath=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await client.storage.from('card-photos').upload(photoPath,photo,{cacheControl:'3600',upsert:false,contentType:photo.type||undefined});if(uploadError)throw new Error(`Photo upload failed: ${uploadError.message}`);button.textContent='Playing Captain…';const {data,error}=await client.rpc('play_captain',{p_card_type:cardType,p_player_one:playerOne,p_player_two:cardType==='dual_power'?playerTwo:null,p_photo_path:photoPath,p_physical_fingerprint:null,p_card_label:cardType==='dual_power'?`${playerOne} + ${playerTwo}`:playerOne});if(error)throw new Error(error.message||'Captain submission failed.');setCaptainMessage('⚡ Captain played! Your card is locked in for this week.',true);button.textContent='✓ Captain Played';resetCaptainForm();await loadLiveState();setTimeout(()=>{button.disabled=false;button.textContent='⚡ Play Captain'},2200);console.log('Captain submission',data)}catch(err){console.error('Captain submit failed',err);if(photoPath){await client.storage.from('card-photos').remove([photoPath]).catch(()=>{})}setCaptainMessage(err.message||'Could not play Captain.');button.disabled=false;button.textContent='⚡ Play Captain'}}
function initCaptainUI(){const type=document.getElementById('cardType');const photo=document.getElementById('cardPhoto');const form=document.getElementById('captainForm');if(type)type.addEventListener('change',()=>{const dual=type.value==='dual_power';document.getElementById('playerTwoLabel').hidden=!dual;if(!dual)document.getElementById('playerTwo').value='' });if(photo)photo.addEventListener('change',()=>{const file=photo.files[0];const preview=document.getElementById('photoPreview');if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}if(!file){preview.hidden=true;document.getElementById('photoName').textContent='Required for Year 1 card verification.';return}previewUrl=URL.createObjectURL(file);preview.src=previewUrl;preview.hidden=false;document.getElementById('photoPrompt').textContent='Card photo selected';document.getElementById('photoName').textContent=file.name||'Ready to upload'});if(form)form.addEventListener('submit',submitCaptain)}
function initAuthUI(){document.getElementById('managerSelect').innerHTML=managers.map(m=>`<option value="${m[1]}">${esc(m[0])}</option>`).join('');document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.authMode)));document.getElementById('authClose').addEventListener('click',closeAuth);document.getElementById('authModal').addEventListener('click',e=>{if(e.target.id==='authModal')closeAuth()});document.getElementById('authSubmit').addEventListener('click',submitAuth);document.getElementById('pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')submitAuth()});document.getElementById('confirmPinInput').addEventListener('keydown',e=>{if(e.key==='Enter')submitAuth()});document.getElementById('authButton').addEventListener('click',async()=>{if(session){if(confirm(`Sign out ${profile?.display_name||''}?`))await client.auth.signOut()}else openAuth('signin')})}
renderNav();initAuthUI();initCaptainUI();renderState();document.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)go(b.dataset.nav)});client.auth.getSession().then(({data})=>handleSession(data.session));client.auth.onAuthStateChange((_event,newSession)=>handleSession(newSession));const initial=location.hash.slice(1);if(baseTabs.some(t=>t[0]===initial)||initial==='admin')setTimeout(()=>go(initial),0);loadLiveState();setInterval(loadLiveState,30000);