const SUPABASE_URL='https://prupedxpebntoqhilrzi.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_TZahmAv5GD3bv4LaHfma_w_i0daueMI';
const tabs=[['home','🏠','Home'],['play','⚡','Play'],['cards','🃏','Cards'],['history','📚','History'],['tickets','🎟️','Tickets'],['rules','📜','Rules'],['admin','🛠️','Admin']];
let state={week:1,demo_mode:true,matchups:[],tickets:[]};

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtScore(v){const n=Number(v);return Number.isFinite(n)?n.toFixed(1):'—'}
function captainLabel(player1,player2,type){if(type==='dual_power'&&player2)return `${player1} + ${player2}`;return player1||'Captain pending'}
function matchupCard(m,i){const a=Number(m.score_a),b=Number(m.score_b),aHas=Number.isFinite(a),bHas=Number.isFinite(b);const aWin=aHas&&bHas&&a>b,bWin=aHas&&bHas&&b>a;return `<article class="panel matchup-card"><div class="matchup-top"><span>MATCHUP ${i+1}</span><span>${state.demo_mode?'DEMO LIVE':esc(m.matchup_status||'LIVE').toUpperCase()}</span></div><div class="team-row ${aWin?'winner':''}"><div><div class="manager-name">${esc(m.manager_a)}</div><div class="captain-name">${esc(captainLabel(m.player_a,m.player_a_two,m.card_type_a))}</div></div><div class="score">${fmtScore(m.score_a)}</div></div><div class="team-row ${bWin?'winner':''}"><div><div class="manager-name">${esc(m.manager_b)}</div><div class="captain-name">${esc(captainLabel(m.player_b,m.player_b_two,m.card_type_b))}</div></div><div class="score">${fmtScore(m.score_b)}</div></div></article>`}
function ticketCards(){return (state.tickets||[]).map((t,i)=>`<article class="panel ticket-card"><span>${i+1}. ${esc(t.name)}</span><span class="mini-ticket">🎟️ ${Number(t.tickets)||0}</span></article>`).join('')}
function renderState(){document.getElementById('matchups').innerHTML=(state.matchups||[]).map(matchupCard).join('')||'<div class="panel">No matchups yet.</div>';document.getElementById('ticketsHome').innerHTML=ticketCards();document.getElementById('ticketsFull').innerHTML=ticketCards();const banner=document.querySelector('.preview-banner');if(banner)banner.textContent=`LIVE SUPABASE DATA · Week ${state.week||1} · ${state.demo_mode?'Demo scoring':'League scoring'} · Unused cards remain private`;const eyebrow=document.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent=`WEEK ${state.week||1} · ${state.demo_mode?'DEMO MODE':String(state.week_status||'OPEN').toUpperCase()}`}
async function loadLiveState(){try{const res=await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_public_card_captain_state`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'Content-Type':'application/json'},body:'{}'});if(!res.ok)throw new Error(`Supabase ${res.status}`);const data=await res.json();if(data&&typeof data==='object'){state=data;renderState()}}catch(err){console.error('Live state load failed',err);const banner=document.querySelector('.preview-banner');if(banner)banner.textContent='LIVE DATA TEMPORARILY UNAVAILABLE · Showing app shell'} }
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));history.replaceState(null,'',id==='home'?location.pathname:`#${id}`);window.scrollTo({top:0,behavior:'smooth'})}
document.getElementById('bottomNav').innerHTML=tabs.map(t=>`<button class="nav-btn ${t[0]==='home'?'active':''}" data-nav="${t[0]}"><span class="ico">${t[1]}</span>${t[2]}</button>`).join('');document.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)go(b.dataset.nav)});const initial=location.hash.slice(1);if(tabs.some(t=>t[0]===initial))go(initial);renderState();loadLiveState();setInterval(loadLiveState,30000);